### ISSUE TITLE
关于硬度约束

### ISSUE THREAD

**Issue by wangsh7** [RollingPlain/ALMFnet#1]
请问代码中的损失函数体现了硬度约束吗，没找到诶，恳请解答

**Comment by RollingPlain** [comment]
你好，在[train_search_lat.py](https://github.com/RollingPlain/ALMFnet/blob/main/train_search_lat.py)文件的144行中，lat参与了上层优化中的结构搜索过程。他和其余损失函数并不同级，故只在[architect.py](https://github.com/RollingPlain/ALMFnet/blob/main/architect.py)中被使用。

**Comment by wangsh7** [comment]
非常感谢您的解答
