### ISSUE TITLE
train_search_lat

### ISSUE THREAD

**Issue by MinLila** [RollingPlain/ALMFnet#3]
Thank you for sharing.
After running step 1 'train_search_lat', the log file was not found. 
I hope to get your help.

**Comment by RollingPlain** [comment]
你好，在模型的类中给出了genotype的定义接口，详见[model_search.py](https://github.com/RollingPlain/ALMFnet/blob/main/model_search.py) 330line。 您可以加载训练后的模型调用该函数来查看搜索结果。

**Comment by MinLila** [comment]
感谢师兄传道授业解惑，祝师兄越来越好


师妹李敏




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RollingPlain/ALMFnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RollingPlain/ALMFnet] train_search_lat (Issue #3)





 
你好，在模型的类中给出了genotype的定义接口，详见model_search.py 330line。 您可以加载训练后的模型调用该函数来查看搜索结果。
